<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;

class AttendanceSession extends Model
{
    use HasUuids;

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'timetable_entry_id',
        'user_id',
        'token',
        'start_time',
        'end_time',
        'is_active',
    ];

    public function timetableEntry()
    {
        return $this->belongsTo(TimetableEntry::class);
    }

    public function openedBy()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function records()
    {
        return $this->hasMany(AttendanceRecord::class);
    }

    /**
     * Check if session has expired and automatically mark alpha
     */
    public function markAlphaIfExpired()
    {
        if (! $this->is_active) {
            return false;
        }

        // Check if current time has exceeded end_time
        if (\Carbon\Carbon::now() <= $this->end_time) {
            return false;
        }

        // Get classroom from timetable entry
        $timetableEntry = $this->timetableEntry;
        if (! $timetableEntry || ! $timetableEntry->template || ! $timetableEntry->template->class) {
            return false;
        }

        $classroom = $timetableEntry->template->class;

        // Get all students in this class
        $studentsInClass = ClassHistory::where('class_id', $classroom->id)
            ->with('student.user')
            ->get()
            ->pluck('student.user')
            ->filter();

        $alphaCount = 0;

        // Mark alpha for students who didn't attend
        foreach ($studentsInClass as $user) {
            if (! $user) {
                continue;
            }
            // If student has ANY attendance record today, skip marking alpha
            $hasAttendedToday = AttendanceRecord::where('user_id', $user->id)
                ->whereDate('scanned_at', \Carbon\Carbon::today())
                ->exists();

            if ($hasAttendedToday) {
                continue;
            }

            // Check if this student already has attendance record for this session
            $hasRecord = AttendanceRecord::where('attendance_session_id', $this->id)
                ->where('user_id', $user->id)
                ->exists();

            if (! $hasRecord) {
                // Create alpha record (user hasn't attended any session today)
                AttendanceRecord::create([
                    'attendance_session_id' => $this->id,
                    'user_id' => $user->id,
                    'status' => 'alpa',
                    'scanned_at' => $this->end_time,
                    $this->end_time,
                    'note' => 'Auto-generated by system (Alpha)',
                ]);
                $alphaCount++;
            }
        }

        // Close the session
        $this->update(['is_active' => false]);

        return $alphaCount;
    }
}
